import { StyleSheet, } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,1)",
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  songSubmission2: {
    margin: 50,
    color: "#22cccc",
    alignItems: 'center',
    fontSize: 35,
  },
  submit: {
    color: "#000",
    fontSize: 15
  },
  placeholder: {
    height: 40,
    width: 250,
    color: '#22cccc',
    borderColor: '#22cccc',
    borderWidth: 3,
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 10,
    marginTop: 20,
    fontSize: 15,
  },
  placeholder1: {
    height: 80,
    width: 250,
    color: '#22cccc',
    borderColor: '#22cccc',
    borderWidth: 3,
    paddingBottom: 40,
    paddingLeft: 10,
    marginTop: 20,
    fontSize: 15,
  },
      header: { height:50, flexDirection: 'row', backgroundColor: "#22CCCC", },
      footer: { height:50, backgroundColor: "#22CCCC", },
      content: { flex: 1, alignItems:'center', },
      userList: { flex: 2, borderColor: '#2cc', borderTopWidth:0.5, },
      elem: {
        width: '100%',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 5,
      },
      elem2: {
        width: '100%',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderColor: '#2cc',
        borderBottomWidth:0.5,
        padding: 7,
      },

      modalContainer: {
        position: 'absolute',
        left: 0,
        right:0,
        top:0,
        bottom:0,
        alignItems: 'center',
        backgroundColor: 'rgba(0,0,0,0.7)',
      },

      modalView: {
        opacity: 1,
        marginTop: '50%',
        width: '60%',
        height: 200,
        backgroundColor: "black",
        borderRadius: 20,
        borderColor: '#2CC',
        borderWidth: 2,
        padding: 15,
        alignItems: "center",
        shadowColor: "#2cc",
        shadowOffset: {
          width: 0,
          height: 2,
        },
        shadowOpacity: 1,
        shadowRadius: 10,
        elevation: 5,
      },

      textInput: {
        height: '22%',
        width: '80%',
        color: "#2cc",
        borderColor: '#2cc',
        borderWidth: 3,
        padding: 10,
        margin: 10,
        textAlign: 'center',
        fontSize:20,
      },

      userInfo: { flexDirection: 'row', alignItems: 'center', },
      userProfile: { width: 50, height: 50, borderRadius: 25, backgroundColor: "#22CCCC", },
      userName: { paddingLeft: 10, },
      userSubmit: { padding: 8, },
      buttonGold: { backgroundColor: "#FFDF00", padding: 10, borderRadius: 5, },
      buttonBlue: { alignItems: 'center', backgroundColor: "#22CCCC", paddingTop:7, paddingBottom:7, paddingLeft:12, paddingRight:12, borderRadius: 5, margin: 60 },
      dummyBox: {backgroundColor: "#22CCCC", padding: 10, borderRadius: 5, },
    });